[project]
name = "nextgenads-backend"
version = "0.1.0"
description = "Backend API for NextGenAds"
authors = ["Shlomi <you@example.com>"]
requires-python = ">=3.11"

dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.27.0"
]
